### ISSUE TITLE
[Question] Always on top?

### ISSUE THREAD

**Issue by guilhermedecampo** [ichord/At.js#321]
Hey @ichord !

Thanks for this awesome package. Just a question.. How can I set the autocomplete always on top?

I'm facing some issues with iOS and the keyboard... I have a list of comments and I'm adding the property bottom on the scroll area and in the input for insert the comment. But from what I saw in the source you search for the window height right?

Thanks a lot!

**Comment by ichord** [comment]
You can use the `reposition` callback to change the position in addition to the keyboard.
This lib was not design for mobile.

**Comment by guilhermedecampo** [comment]
Ok man I did some workaround.

**Comment by fritx** [comment]
If the view is not visible, calling reposition will cause such error:

```plain
TypeError: Cannot read property 'bottom' of undefined
    at View.reposition (webpack:///./app/src/common/jquery.atwho.js?:1037:15)
    at App.reposition (webpack:///./app/src/common/jquery.atwho.js?:1188:23)
    at HTMLDivElement.eval (webpack:///./app/src/common/jquery.atwho.js?:1216:37)
    at Function.jQuery.extend.each (webpack:///./~/jquery/dist/jquery.js?:365:19)
    at jQuery.fn.jQuery.each (webpack:///./~/jquery/dist/jquery.js?:137:17)
    at $.fn.atwho (webpack:///./app/src/common/jquery.atwho.js?:1208:82)
    at EditorForm.onWinResize (webpack:///./app/src/components/EditorForm.js?:199:40)
    at Window.debounced (/Users/dji/GT/app/node_modules/lodash/index.js:7737:27)
    at emitTwo (events.js:90:20)
    at Window.emit (events.js:153:7)
```

**Comment by fritx** [comment]
I managed to fix it by extending an Api for detection before reposition.

```js
onWinResize() {
+ // if ($('.atwho-view').is(':visible')) {
+ if ($('#editor').atwho('isVisible')) {
    $('#editor').atwho('reposition')
+ }
}

// jquery.atwho.js
Api = {
  // ...
+ isVisible: function() {
+   var c;
+   if (c = this.controller()) {
+     return c.view.visible();
+   }
+   return false;
+ },
}
```

**Comment by reepush** [comment]
That was fun 😊

```js
$('[data-at-mentions]').atwho({
  at: "@",
  data: data,
  callbacks: {
    beforeReposition: function(offset) {
      offset.left = this.rect().left
      offset.top = this.rect().top - this.$el.children().height() 
    }
  }
})
```
